#!/usr/bin/env bash

SCRIPT_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )"

PRIVATE_IP=$(aws ec2 describe-instances | jq -r '.Reservations[].Instances[].NetworkInterfaces[].PrivateIpAddress')
ssh -i "${SCRIPT_DIR}/../secrets/ssh_key" ubuntu@${PRIVATE_IP}
